stages:
   - pre-deploy
   - deploy
stage-build:
      image: php:7.3
      stage: pre-deploy
      only:            
         - merge_requests
         - main
      # rules:
         # - if: $CI_COMMIT_TAG != "deploy"
         # - if: $CI_COMMIT_BRANCH == "main"
      before_script:
         - mkdir -p ~/.ssh/
         - echo "${CI_KNOWN_HOSTS}" > ~/.ssh/known_hosts
         - echo "${DEPLOY_KEY}" > ~/.ssh/id_rsa
         - chmod 600 ~/.ssh/id_rsa
         - sudo apt install composer -y
         - git config --global user.name "${GITLAB_USER_NAME}"
         - git config --global user.email "${GITLAB_USER_EMAIL}"
         - git remote remove ssh_origin || true  # Local repo state may be cached
         - git remote add ssh_origin "git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git"
      script:
         - echo ${CI_PIPELINE_SOURCE}
         - echo ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
         - echo ${CI_COMMIT_TAG}
         - echo ${CI_COMMIT_BRANCH}
         - echo ${CI_DEPLOY_USER}
         - touch test.log
         - echo "test${CI_COMMIT_TIMESTAMP}" > test.log
         - git add test.log
         - git commit -m 'deploy' test.log
         - git push ssh_origin HEAD:main 
stage-deploy:
        stage: deploy
        script:
            - cd /var/www/prjctr & git checkout HEAD:main & git pull https://gitlab-ci-token:${CI_JOB_TOKEN}@$CI_SERVER_HOST:$CI_PROJECT_PATH.git