stages:
   - build
   - deploy
stage-build:
      image: php:7.3
      stage: build
      before_script:
         - sudo apt install composer -y
      script:
         - git checkout main
         - composer -v
         - touch test.log
         - echo 'test-ok' > test.log
         - git add test.log
         - git commit -m 'stage deploy release' test.log
         - git push
#stage-deploy:
#        stage: deploy
#        script:
#            - sudo mkdir /var/www/prjctr/gitlab_test
#            - sudo touch /var/www/prjctr/gitlab_test/test
#            - sudo bash -c 'echo "test" > /var/www/prjctr/gitlab_test/test'