stages:
   - deploy
stage-deploy:
        stage: deploy
        script:
            - mkdir /var/www/prjctr/gitlab_test
            - touch /var/www/prjctr/gitlab_test/test
            - echo "test" > /var/www/prjctr/gitlab_test/test
