stages:
   - test
   - build
   - deploy
test:
   image: php:7.3-fpm
   stage: test
   only:
    - merge_requests
   before_script:
      - curl -sS https://getcomposer.org/installer -o composer-setup.php && php composer-setup.php --2 --install-dir=bin --filename=composer && mv composer.phar /usr/local/bin/composer
      - composer -v
   script:
      - composer up
      # here can be some tests added
build:
   image: php:7.3-fpm
   stage: build
   rules:
      - if: $CI_COMMIT_AUTHOR == "gitlab-ci <gitlab-ci@pmi.bet>"
        when: never
      - if: $CI_COMMIT_BRANCH == "main"
        when: always
   before_script:
      - curl -sS https://getcomposer.org/installer -o composer-setup.php && php composer-setup.php --2 --install-dir=bin --filename=composer && mv composer.phar /usr/local/bin/composer
      - composer -v
      - git config --global user.name "gitlab-ci" && git config --global user.email "gitlab-ci@pmi.bet"
      - mkdir -p ~/.ssh/ && echo "${CI_KNOWN_HOSTS}" > ~/.ssh/known_hosts && echo "${DEPLOY_KEY}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      - git remote remove ssh_origin || true  # Local repo state may be cached
      - git remote add ssh_origin "git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git"
   script:
      - composer up
      - git diff-index --quiet HEAD -- || git commit -m "deploy ${CI_COMMIT_TIMESTAMP}" -a && git push ssh_origin HEAD:main;
deploy:
   rules:
      - if: $CI_COMMIT_AUTHOR == "gitlab-ci <gitlab-ci@pmi.bet>"
        when: never
      - if: $CI_COMMIT_BRANCH == "main"
        when: always
   stage: deploy
   script:
      - cd /var/www/prjctr && sudo composer release