stages:
   - test
   - build
   - deploy
test:
   image: php:7.3
   stage: build
   only:
    - merge_requests
   before_script:
      - sudo apt install composer -y
   script:
      - composer up
stage-build:
   image: php:7.3
   stage: build
   only: 
      - main
   before_script:
      - mkdir -p ~/.ssh/
      - echo "${CI_KNOWN_HOSTS}" > ~/.ssh/known_hosts
      - echo "${DEPLOY_KEY}" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - sudo apt install composer -y
      - git config --global user.name "${GITLAB_USER_NAME}"
      - git config --global user.email "${GITLAB_USER_EMAIL}"
      - git remote remove ssh_origin || true  # Local repo state may be cached
      - git remote add ssh_origin "git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git"
   script:
      - composer up
      - git diff-index --quiet HEAD -- || git commit -m "deploy ${CI_COMMIT_TIMESTAMP}" -a && git push ssh_origin HEAD:$CI_DEFAULT_BRANCH;
stage-deploy:
   only: 
      - main
   except:
    refs:
        - merge_requests
   stage: deploy
   before_script:
      - git config --global --add safe.directory /var/www/prjctr
   script:
      - cd /var/www/prjctr && sudo composer release