stages:
   - build
   - deploy
stage-build:
      image: php:7.3
      stage: build
      before_script:
         - sudo apt install composer -y
         - git config --global user.name "${GITLAB_USER_NAME}"
         - git config --global user.email "${GITLAB_USER_EMAIL}"
      script:
         - git checkout ${CI_DEFAULT_BRANCH}
         - git pull
         - git remote remove upstream || true
         - git remote add upstream $REMOTE_URL
         - git fetch upstream
         - git merge upstream/$REMOTE_BRANCH
         - git push "https://${GITLAB_USER_LOGIN}:${CI_JOB_TOKEN}@${CI_REPOSITORY_URL#*@}" "HEAD:${CI_DEFAULT_BRANCH}"
#stage-deploy:
#        stage: deploy
#        script:
#            - sudo mkdir /var/www/prjctr/gitlab_test
#            - sudo touch /var/www/prjctr/gitlab_test/test
#            - sudo bash -c 'echo "test" > /var/www/prjctr/gitlab_test/test'