stages:
   - build
   - deploy
stage-build:
    stage: build
    image: ubuntu:20.04
    script:
        - mkdir build
        - cd build
        - echo "test" > test.log
    artifacts:
        paths:
            - "build/"
        expire_in: 30 days
stage-deploy:
        stage: deploy
        tags: 
            - deploy
        script:
            - touch file1
            - echo "Test" > file1
