stages:
   - build
   - deploy
stage-build:
      image: php:7.3
      stage: build
      script:
         - ls
#stage-deploy:
#        stage: deploy
#        script:
#            - sudo mkdir /var/www/prjctr/gitlab_test
#            - sudo touch /var/www/prjctr/gitlab_test/test
#            - sudo bash -c 'echo "test" > /var/www/prjctr/gitlab_test/test'