stages:
   - deploy
stage-deploy:
        stage: deploy
        script:
            - sudo mkdir /var/www/prjctr/gitlab_test
            - sudo touch /var/www/prjctr/gitlab_test/test
            - sudo echo "test" > /var/www/prjctr/gitlab_test/test
