stages:
   - build
   - deploy
stage-build:
      image: php:7.3
      stage: build
      before_script:
         - mkdir ~/.ssh/
         - echo "${CI_KNOWN_HOSTS}" > ~/.ssh/known_hosts
         - echo "${DEPLOY_KEY}" > ~/.ssh/id_rsa
         - chmod 600 ~/.ssh/id_rsa
         - sudo apt install composer -y
         - git config --global user.name "${GITLAB_USER_NAME}"
         - git config --global user.email "${GITLAB_USER_EMAIL}"
         - git remote remove ssh_origin || true  # Local repo state may be cached
         - git remote add ssh_origin "git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git"
      script:
         - git checkout "HEAD:${CI_DEFAULT_BRANCH}"
         - git pull
         - touch test.log
         - echo 'test' > test.log
         - git add test.log
         - git commit -m 'deploy' test.log
         - echo 'test'
         - git push "HEAD:${CI_DEFAULT_BRANCH}"
#stage-deploy:
#        stage: deploy
#        script:
#            - sudo mkdir /var/www/prjctr/gitlab_test
#            - sudo touch /var/www/prjctr/gitlab_test/test
#            - sudo bash -c 'echo "test" > /var/www/prjctr/gitlab_test/test'